name: 逗比章鱼的藏书阁
description: 个人日志，读书笔记集散地
meta_description: "个人日志，读书笔记集散地"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://alex-marmot.github.io'

# Details for the RSS feed generator
url:            'blog url'
author:         'alex'
